# Generated by Django 5.1.1 on 2024-11-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
