# Generated by Django 5.1.1 on 2024-11-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_firstname_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_calories', models.FloatField(blank=True, default=0.0)),
                ('last_protein', models.FloatField(blank=True, default=0.0)),
                ('last_carbs', models.FloatField(blank=True, default=0.0)),
                ('last_fats', models.FloatField(blank=True, default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
