# Generated by Django 5.1.1 on 2025-01-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_birthdate_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_calories',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_carbs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_fats',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_protein',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
