# Generated by Django 5.1.1 on 2025-01-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tier',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
