# Generated by Django 5.1.1 on 2025-01-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Brust'), ('back', 'Rüken'), ('legs', 'Beine'), ('shoulders', 'Schultern'), ('arms', 'Arme'), ('abs', 'Bauch')], max_length=50),
        ),
    ]
